build:
    image: crossdev/go-web-tester
    commands:
        - apt-get -y install xz-utils
        - export GOPATH=$GOPATH:/drone
        - make install
        - sudo -u nobody make e2e

publish:
    dockerhub:
        token: $$HUB_TOKEN
        repo: crossdev/arch-repo-server
